##build on baseEnv: 45 seconds save;
FROM registry.cn-shenzhen.aliyuncs.com/sam-ns1/barge-os:src as src

#version
ENV ver-ss=v1.0

ENV BR_ROOT=/build/buildroot
WORKDIR ${BR_ROOT}
RUN sh /build/scripts/build.sh
#ADD build.sh /
#RUN sh /build.sh


##copy dist file: lite images size;
FROM infrastlabs/alpine-ext
MAINTAINER sam <sldevsir@126.com>

USER root
##data.tar.gz trafix.helm
COPY --from=src /build/buildroot/output /output

##run as root
USER root
WORKDIR /


